import { Nunito, Playfair_Display } from "next/font/google";

import "./globals.css";
import Providers from "./providers";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const nunito = Nunito({ weight: "400", subsets: ["latin"] });
const playfair_display = Playfair_Display({
	weight: ["400", "500", "700"],
	subsets: ["latin"],
	variable: "--playfair_display_font",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="light">
			<body
				className={`${nunito.className} ${playfair_display.variable}`}
			>
				<Providers>
					<Navbar />
					{children}
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
